services:

  # main bolna service
  bolna-app:
    image: bolna-app:latest
    build:
      context: .
      dockerfile: dockerfiles/bolna_server.Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - redis
    env_file:
        - .env
    volumes:
      - ../agent_data:/app/agent_data
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
      - $HOME/.aws/config:/root/.aws/config:ro

  # redis service used as a persistent storage
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # ngrok for local tunneling
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok-config.yml:/etc/ngrok.yml
    ports:
      - 4040:4040

  ### Telephony servers ###
  twilio-app:
    image: twilio-app:latest
    build:
      context: .
      dockerfile: dockerfiles/twilio_server.Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - ngrok
      - bolna-app
    env_file:
      - .env

  plivo-app:
    image: plivo-app:latest
    build:
      context: .
      dockerfile: dockerfiles/plivo_server.Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - redis
      - ngrok
      - bolna-app
    env_file:
      - .env
