region: us
version: "2"
authtoken: 2YBEGhRjtqbxbyUYb8HosUivMuq_7hV4wXk7No9Jo6CyfptPh
tunnels:
  twilio-app:
    addr: twilio-app:8001
    proto: http
  bolna-app:
    addr: bolna-app:5001
    proto: http
